<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



In [2]:
import sys
import numpy as np

## Creating Numpy Arrays from Python Lists

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point)

In [4]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Unlike Python lists, NumPy arrays can explicitly be **multi-dimensional**

In [6]:
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

In [7]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

### `zeros`, `ones`, `full`, `arange`, `linspace`

In [8]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### `random` 

In [13]:
np.random.seed(0)  # seed for reproducibility

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [14]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.26611853, -0.50587654,  2.54520078],
       [ 1.08081191,  0.48431215,  0.57914048],
       [-0.18158257,  1.41020463, -0.37447169]])

In [57]:
np.random.randint(10, size=3)

array([9, 0, 9])

In [52]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 3, 2],
       [0, 8, 8],
       [3, 8, 2]])

### `eye`, `empty`

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(3, dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [18]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## NumPy Array Attributes

In [19]:
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [20]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [21]:
print("dtype:", x3.dtype)

dtype: int64


- `itemsize`, which lists the size (in bytes) of each array element, and 
- `nbytes`, which lists the total size (in bytes) of the array

In [22]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Indexing & Slicing
### One-dimensional subarray

In [23]:
x1 = np.random.randint(20, size = 6) # One-dimensional array

In [24]:
x1

array([ 0, 10, 18, 11,  2,  2])

In [25]:
x1[4], x1[-1]

(2, 2)

### Slicing:
`x[start:stop:step]`

In [26]:
x1[:3] #First 3 Element

array([ 0, 10, 18])

In [27]:
x1[4:5]  # middle sub-array

array([2])

In [28]:
x1[::2]  # every other element, every 2 step

array([ 0, 18,  2])

### Multi-dimensional array

In [29]:
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array

In [30]:
x2

array([[3, 3, 2, 3],
       [4, 1, 2, 9],
       [1, 4, 6, 8]])

In [31]:
x2[2,0]

1

In [32]:
x2[2,0] = 11

In [33]:
x2

array([[ 3,  3,  2,  3],
       [ 4,  1,  2,  9],
       [11,  4,  6,  8]])

In [34]:
x2[:2, :3]  # two rows, three columns

array([[3, 3, 2],
       [4, 1, 2]])

In [35]:
print(x2[:, 0])  # first column of x2

[ 3  4 11]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Reshaping of Arrays

In [36]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
x = np.array([1, 2, 3])

In [38]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Concatenation and Splitting

In [39]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [40]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [41]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [42]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [43]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [44]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

In [45]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [46]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
A[:2, :2]

NameError: name 'A' is not defined

In [ ]:
A[:2, 2:]

In [ ]:
A

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

In [ ]:
A[2] = 99

In [ ]:
A

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
a.var()

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

In [ ]:
A.mean()

In [ ]:
A.std()

In [ ]:
A.sum(axis=0)

In [ ]:
A.sum(axis=1)

In [ ]:
A.mean(axis=0)

In [ ]:
A.mean(axis=1)

In [ ]:
A.std(axis=0)

In [ ]:
A.std(axis=1)

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

![image-broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [49]:
a = np.arange(3)

In [ ]:
a

In [50]:
a + 5 #Broadcasting & Vectorized operations

array([5, 6, 7])

In [ ]:
a * 10

In [ ]:
a

In [ ]:
a += 100

In [ ]:
a

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
b

In [ ]:
a + b

In [ ]:
a * b

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a[0], a[-1]

In [ ]:
a[[0, -1]]

In [ ]:
a[[True, False, False, True]]

In [ ]:
a

In [ ]:
a >= 2

In [ ]:
a[a >= 2]

In [ ]:
a.mean()

In [ ]:
a[a > a.mean()]

In [ ]:
a[~(a > a.mean())]

In [ ]:
a[(a == 0) | (a == 1)]

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [ ]:
A > 30

In [ ]:
A[A > 30]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

In [ ]:
A @ B

In [ ]:
B.T

In [ ]:
A

In [ ]:
B.T @ A

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

In [ ]:
np.dtype(float).itemsize

### Lists are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)